prestashop:
  container_name: jira-pro-1700.hipay-pos-platform.com
  build: .
  ports:
    - "8100:80"
  links:
    - smtp
  env_file:
    - env
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-ps-refonte
  ports:
    - "1100:1080"