prestashop:
  container_name: jira-ps-refonte.hipay-pos-platform.com
  build: .
  ports:
    - "8094:80"
  links:
    - mysql
    - smtp
  env_file:
    - env
mysql:
  container_name: mysql-hipay-ps-refonte
  image: mysql:5.6.23
  env_file:
    - env
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-ps-refonte
  ports:
    - "1094:1080"